dist: trusty
language: scala
scala:
  - 2.12.10
jdk:
  - oraclejdk8
services:
  - docker
before_deploy:
  - pip install --user release-manager==0.4.1
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
script:
  - sbt test
deploy:
  - provider: script
    script: release-manager --config ./.travis/release.yml --check-version --make-artifact --make-version --upload-artifact
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: sbt "project kinesis" docker:publish && sbt "project kafka" docker:publish && sbt "project nsq" docker:publish
    skip_cleanup: true
    on:
      tags: true
env:
  global:
  - secure: oiJy2eHeL29hsDpzxJO1hIa0d4sKa7YRedkQXAGKO2aFbXsHWuio19NM8LmpThMFBqA9CoJ9J6NHh1/ERn/yIySvc5/vPbh+u8FoOwCiZVIO4NNvEcbvQr0B0j9p2oXjonh22QbsI0BbcA8FFRfeS8RhyN3vtTa+XwBtL8fkZT0hIB193LorjGGnQIX2SLdYvH6ZzCC5B2wKL4nqHI3TpqAoyfz6DjwlmPuqBiHABuuVY4Sqv4fjb1J7TGrJpCxjS9lYVNES8WAk/0PRC2s69BOPyM9KGkhOg8qR602gTOMHak2Ptfy0NXqo/nN4Dg+CIoa/TiqjF3q7P+xv9UGDQchqasx9FJ/YriAzzjegC6n5rKERpK3Bwy/2QkScFGSmB0WXWZlkjM/kQ82k5lHJOUTGcwQNYLVMNZTeJ88MkWndODR8JAvXY1VNp5+VwkdIToyIEWFyxBv7mRimezzYaYlaIj0cYyDKYKNRS0Gi82C+oZljGn2+uaSSR/KvQRM0i8JTXdeS8taoI1+FHlA8n0qFyvyo4goY/ZXb8fXKTDO0FEfRvQnBMWMj1bR5ANoOcrTYVUYXP3cFUYy5OXsHqjFcGwn5YCD53cPEwB5ZC3tIM0UzDaF7TxdxxvMonlFxICtAOGHVUHE/IFj9/++iK4eIDnV4Ace4gRNvkM9QBsc=
  - secure: bcEJSjYHndYS/vyI2i6CuoS7gGEIzGfYDf4VlOah+/Pmr6ZOVMiZPHdOTyR2JMlnjGpSwf3WBtXGIAYmnx+XsrlTiGBFLrlBt0XTJ6bZQLi0BzRZoS2TqaogcgEZBgqX2ZNAuWjjT7hkbBTiRyGG6knhci2CUVvIzhhSvvj4ZGDNDcYYb7wfYGfhfHkNoXS26dn1/9k602PuRB8canCj8ObCkYJPHBmValEYejXDJy2IbAbGxcmXlCtsuKppAgmOhqHUdFRDm2fBL+4WPRZ23xUAo7b24GWtDczWxUAI6sUh8kei5AEaV7SXXs60g2fnyItLqs55BP+YgGCFpTGRKoDfY5J8gnmfEIthjpQAhxrqVA8/wEywRoG5rZZ3P8+69uGem6VJs3/Yrg7ThSxPtilKagzYqZm0jLmLPumy4Lv0i9tQAcEuKXV8wte9H2AkGjiOkOeGSuI3Yk1t1ovWJ7/AQ6c6esVVJeehRBBzmVyiVBn+nggIMrOek4PNsJNCfDjYq+xV+JXMigFLhADNu1tXPO4bnWN1m9bKv7bnUGup6MEv7wpjxUSkHGhpNmhq/3mKQkb/9JBdjxV5m1vE1wkgC41o3wUZCBg/ojkuOefkCBRRVUHjhL8QTfnLhOQr+Qm/aqnI4XtJkGG1/0YP3O5+4ZwJfbi24oJagHtnGgs=
  - secure: GIRKB98H6LWkYdrTJjTWFLi7aCclrAk5KWj4shVfmquikLBm5MwEWG6osjl5nxXIGDayzo6oJuehdwQY+D6nUgWveVCdT0fztdS+wyyp3ocfiDZsNHsXRT0sw3Q45cXTQYllxdzkt40V0ToXnR9inCp2B6COkPgG8yY2j7piDt5yVdbrczEKVOeYWMkRs1uUfpst7UDqt9Ei6hSrusrvRfEVxixtFN1w9S2q55Ot4+2r0Zi3SbQju0pj06UhwV5txS8N+CEM0q+RjXhRIQKMjcpzewYgUeIOlL/hNC5nlaZe4ob3UTyotKbLPGsBYKE9qP+1GyH7pOBf2AvzNyF49SZPkbZrzG9qjohicgZOIRCFALKy1v7F2Kdkt+Du/g4i3TFvJnJU45F3N6i0VizWfvYPDvnEXatUIs37N7XIYyZbpar0lSpZm8iJ565D1rBRvZuHqp+Nlf96GCicJGXTKq8tczDHqPaD+IWTwOz2/v8YBA9v3BxuQB1g8BT9pnQ9evVkkEV/9AQy187rVnsqh3vFQpQs625nQ5akODKCvdEpg3ig5SB5ywGbnNBQDpUU2VctW+EMX5wbj9W5td5Y90a8C02gZTZ41HM3chIouEQFAOb/h0WA3ZZWRGUahDozFsafhjyi0wofvKa8xhEqWbyCRIbge/QdmFo0zrKlNr4=
  - secure: c4jJ/FHBc3iVOzXWj1EP2GkzCAHWb3WnD5386nuiXDlb9uQFQEq4btdk4AlCKbCDXkXNFeMjRDr1w84SUqA+aK6zWNr2LvpoqpW4MIcPINJuX1v0PDHRuTes3G7+ClipFWIZMGIH1YjLraM3CTjsUATbqf+yznoBW2xLDVH5x7EwHMDjmKuL/LONgl0DjazF//RCTqllqBtwLsR8uuzIK4VPA3d6iCkaKiUuiQY/6tRXLgbyL6YicS6ZULQ/7nya+hccxMW1td9IliDoX+Z2urPVZJsTNfwVkD7p7mwrORsgx+HcS6GZnQmi+StW7DuP2EDuKZR+uVnOHudu4c6rXEf+ZsZjbPV1rLYu3letBjILpPk3tTDdsMwEIIrkunJZhll+akGoR+YuHm1KYvvN83n4XCCwSOV7kZ86VlFmqy9GJHK6Hlu6/sZqgydMabEO9MNet2mmxsXAD0I8z3nP7cRvOMvxFcEgvp9J+Sy5K6Z/G+wz68iwqys5NzARckQjqb10/nnuyYiL3kNX6qB55YIA4Fvrpw+6RX9ybVv87/A6Hnvrrn4rQZWVD1q3sMSuJhJJuzDxoGn0JUUb/dEDjP59TPTvSmAUYbv7YbKWDe8QbU44G4wj6ESfNwMnRbUCzfIyDJj/zI0qHU7hzI5El3GhomnEgnLwyCXgZlq91kY=
