---
# --- Variables --- #

local :
  root_dir : <%= ENV['TRAVIS_BUILD_DIR'] %>

# --- Release Manager Config --- #

# Required: deployment targets
targets :
  - type : "bintray"
    user : <%= ENV['BINTRAY_SNOWPLOW_GENERIC_USER'] %>
    password : <%= ENV['BINTRAY_SNOWPLOW_GENERIC_API_KEY'] %>

# Required: packages to be deployed
packages :
  - repo : "snowplow-generic"
    name : "snowplow-stream-enrich"
    user_org : "snowplow"
    publish : true
    override : false
    continue_on_conflict : false
    version : <%= FUNC['sbt_version(.)'] %>
    build_version : <%= ENV['TRAVIS_TAG'] %>
    build_commands :
      - sbt "project kinesis" assembly
      - sbt "project kafka" assembly
      - sbt "project nsq" assembly
    artifacts :
      - type : "zip"
        prefix : "snowplow_stream_enrich_kinesis_"
        suffix : ""
        binary_paths :
          - "kinesis/target/scala-2.12/snowplow-stream-enrich-kinesis-{{ packages.0.build_version }}.jar"
      - type : "zip"
        prefix : "snowplow_stream_enrich_kafka_"
        suffix : ""
        binary_paths :
          - "kafka/target/scala-2.12/snowplow-stream-enrich-kafka-{{ packages.0.build_version }}.jar"
      - type : "zip"
        prefix : "snowplow_stream_enrich_nsq_"
        suffix : ""
        binary_paths :
          - "nsq/target/scala-2.12/snowplow-stream-enrich-nsq-{{ packages.0.build_version }}.jar"
